language: php

dist: xenial

addons:
  apt:
    packages:
      - tidy

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    # Framework tests
    - php: '7.2'
      env: DB=MYSQL SUITE=Core
      services:
       - mysql

before_script:
 # Fix bug in Selenium with duplicate localhost definitions: https://github.com/travis-ci/travis-ci/issues/3054
 - "sed 's/localhost localhost/localhost/' /etc/hosts > /tmp/etchoststmp && cat /tmp/etchoststmp | sudo tee /etc/hosts"

 - export CORE_RELEASE=$TRAVIS_BRANCH
 - composer self-update || true
 - phpenv rehash
 - phpenv config-rm xdebug.ini || true
 - echo 'memory_limit = 3G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit --testsuite "$SUITE"

after_failure:
 - php ~/travis-support/travis_upload_artifacts.php --if-env BEHAT_TEST,ARTIFACTS_KEY --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/
